language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - nightly
  - hhvm
  - hhvm-nightly
before_script:
  - composer install
matrix:
  fast_finish: true
  allow_failures:
    - php:
      - nightly
      - hhvm
      - hhvm-nightly